### PR TITLE
wait for file_server ready to avoid timing issue

### LINKED ISSUE #28: Testcase TestObtainFromKnownLocation intermittently failed as file_server was not ready
It seems like a timing issue. The code started the file server in a background goroutine. The server might not be ready when the code tried to connect.

func testArchiveSource(t *testing.T, tc obtainTestCase) {
	cleanup(tc.targetDir)
	defer cleanup(tc.targetDir)
	**server := testCommon.StartStaticFileServer(t)**
	defer testCommon.ReportOnError(t, func() error { return server.Shutdown(context.TODO()) })
	source := NewArchiveSource(tc.url, tc.targetDir)
	runner := test.NewMockRunner()
	runner.PrepareCommandExpectation(tc.expectedCommands)
	fs := runner.GetFileSystem().(*test.MockFileSystem)
	fs.PrepareChdir(tc.expectedChdir)
	if tc.getWdErr != nil {
		fs.On("Getwd").Return("home", *tc.getWdErr).Once()
	}
	**err := source.Obtain(runner)**

### PR DESCRIPTION
**Pull request by northtyphoon**
**Purpose of the PR:**

**Fixes #28** 

**Notes/Details:**

The fix pings the file server to test the connection after it's started.

@sajayantony @shhsu

### CODE REVIEW

File: tests/testCommon/file_server.go [hunk 1]
```diff
@@ -29,9 +31,30 @@ func StartStaticFileServer(t *testing.T) *http.Server {
...
+	err := WaitForServerReady(10)
+	if err != nil {
+		t.Fail()
+	}
+
 	return server
 }
 
+// WaitForServerReady waits for server ready until timeout
+func WaitForServerReady(timeoutInSeconds uint) error {
```
Comment (shhsu) [inline tests/testCommon/file_server.go]: After some quick research, apparently the right thing to do is not use ListenAndServe at all.
http://grokbase.com/t/gg/golang-nuts/141ee4dqyg/go-nuts-how-to-know-when-listenandserve-is-ready-to-handle-connections
Would you like to modify with this solution?

Comment (northtyphoon) [reply tests/testCommon/file_server.go]: Thought about it, current solution based on client pulling also works for ListenAndServeTLS if we want to test https in the future.
