### PR TITLE
Return an error if the Task's version is invalid

### LINKED ISSUE #418: Deprecate invalid versions and throw exceptions
2 months from this issue's creation time, start throwing errors if the version specified within a `Task` is invalid.

### PR DESCRIPTION
**Pull request by ehotinger**
**Purpose of the PR:**
- Return an error if the Task's version is invalid

**Fixes #418**

### CODE REVIEW

File: graph/task.go [hunk 1]
```diff
@@ -326,20 +331,13 @@ func mergeEnvs(dest []string, src []string) ([]string, error) {
...
-		version = currentTaskVersion
-	}
-
+// validateTaskVersion validates the specified version and returns an error if it isn't valid.
+func validateTaskVersion(version string) error {
 	vLower := strings.ToLower(version)
 	if _, ok := validTaskVersions[vLower]; !ok {
-		log.Printf("WARNING: invalid version specified: %s - defaulting to %s instead...\n", version, currentTaskVersion)
-		version = currentTaskVersion
+		return fmt.Errorf("invalid version specified: %q", version)
```
Comment (northtyphoon) [inline graph/task.go]: Can you print out currentTaskVersion as well?
