### PR TITLE
check exchange api response and return the appropriate error

### LINKED ISSUE #613: The error message is misleading if identity doesn't have permission on the registry
If the identity doesn't have the permission to access the registry, the code will display the following error message

`failed to login, ran out of retries: failed to set docker credentials: Error: Cannot perform an interactive login from a non TTY device`

It's because current code didn't check the response status code of ACR exchange api. The code ends up passing an empty password string to docker login command.

https://github.com/Azure/acr-builder/blob/c94aeab189108160b2c60554cd82b63a1010e4bc/tokenutil/token_util.go#L54

### PR DESCRIPTION
**Pull request by northtyphoon**
**Purpose of the PR**

- properly handle status code from ACR exchange api

Fixes #613

### CODE REVIEW

File: tokenutil/token_util.go [hunk 1]
```diff
@@ -47,25 +47,29 @@ func GetRegistryRefreshToken(registry, resourceID, clientID string) (string, err
...
 	if err != nil {
-		return "", errors.Wrap(err, "unable to create an HTTP post request to exchangeAPI")
+		return "", errors.Wrap(err, "unable to create the request to get ACR refresh token")
 	}
 	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
 
 	response, err := client.Do(req)
 	if err != nil {
-		return "", errors.Wrap(err, "unable to make post request to exchangeAPI")
+		return "", errors.Wrap(err, "unable to make the request to get ACR refresh token")
```
Comment (estebanreyl) [inline tokenutil/token_util.go:56]: unable to make sounds a bit odd. Should we do "unable to send..." instead, it seems more clear

**Review by estebanreyl — APPROVED** [review]
LGTM
