### PR TITLE
Don't query digests if the base image is scratch

### LINKED ISSUE #99: Build fails when using scratch as a base image
BUG

**What happened?**:
Building with a docker file using scratch fails the build. 

```
tarting to stream the logs...
time="2018-04-12T21:23:06Z" level=info msg="Running command docker login -u 00000000-0000-0000-0000-000000000000 --password-stdin sajayeus.azurecr.io"
Login Succeeded
time="2018-04-12T21:23:06Z" level=info msg="Running command docker build --pull -f Dockerfile -t sajayeus.azurecr.io/test ."
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM scratch
 --->
Step 2/2 : COPY Dockerfile ./Dockerfile
 ---> ccfbf655409b
Successfully built ccfbf655409b
Successfully tagged sajayeus.azurecr.io/test:latest
time="2018-04-12T21:23:07Z" level=info msg="Running command docker push sajayeus.azurecr.io/test"
The push refers to repository [sajayeus.azurecr.io/test]
875f044d742b: Preparing
875f044d742b: Pushed
latest: digest: sha256:4776d03fc86feb8fb819c60f2c7a63fa5c53f36b48fd2c3720bf724eb93db844 size: 524
time="2018-04-12T21:23:26Z" level=info msg="Running command docker inspect --format \"{{json .RepoDigests}}\" sajayeus.azurecr.io/test"
"["sajayeus.azurecr.io/test@sha256:4776d03fc86feb8fb819c60f2c7a63fa5c53f36b48fd2c3720bf724eb93db844"]"
time="2018-04-12T21:23:26Z" level=info msg="Running command docker inspect --format \"{{json .RepoDigests}}\" scratch"
Error: No such object: scratch
time="2018-04-12T21:23:26Z" level=error msg="Failed to run command: exit status 1"
```

**How do you reproduce it (as minimally and precisely as possible)?**:

Use the following docker file 
```
FROM scratch
COPY Dockerfile ./Dockerfile
```

az acr build -t test -c . -r myregistry 

**Environment**:
ACR  Builder

### PR DESCRIPTION
**Pull request by ehotinger**
**Purpose of the PR:**

Don't query digests if the base image is `scratch`.

**Fixes #99**

**Notes/Details:**

```
[
    {
        "image": {
            "registry": "ehotinger.azurecr.io",
            "repository": "eric",
            "tag": "latest",
            "digest": "sha256:d096e3a5ec1792e0c1ca84097694e9c08535797b643c404a7150c7a42232a523"
        },
        "runtime-dependency": {
            "registry": "registry.hub.docker.com",
            "repository": "scratch",
            "tag": "latest",
            "digest": ""
        },
        "buildtime-dependency": null
    }
]
```

### CODE REVIEW

**Comment by ehotinger** [comment]
@djyou  + @northtyphoon this will be a very special case for base image updates, please review the above  output and figure out the auto update story.

File: pkg/commands/docker.go [hunk 1]
```diff
@@ -205,6 +205,14 @@ func PopulateDigests(runner build.Runner, dependencies []build.ImageDependencies
 func queryDigest(runner build.Runner, reference *build.ImageReference) error {
 	if reference != nil {
 		refString := reference.String()
+
+		// refString will always have the tag specified at this point.
+		// For "scratch", we have to compare it against "scratch:latest" even though
+		// scratch:latest isn't valid in a FROM clause.
+		if refString == build.NormalizeImageTag(constants.NoBaseImageSpecifier) {
```
Comment (northtyphoon) [inline pkg/commands/docker.go]: Since it's a special case and you already put very detailed comments, do you think 
`if refString == "scrath:latest"` is more clear?

**Comment by northtyphoon** [comment]
For auto-update, we should be good as we don't track `scratch` and therefore no push notification. Just make sure later on we don't update the watch list and add `scratch` =)

**Comment by ehotinger** [comment]
@northtyphoon great! I updated it to just use a const and avoid the func, initially I wanted to preserve the identical const from `moby/moby` for clarity but it's NBD. :peanuts:

**Comment by coveritytest** [comment]
Error still exists:

2022-01-21T16:11:14.2683325Z [command]/usr/bin/docker pull scratch
2022-01-21T16:11:14.4068768Z Error response from daemon: 'scratch' is a reserved name
...
2022-01-21T16:11:14.4508252Z Error: No such object: scratch
