### PR TITLE
handle quotes for docker build step args

### LINKED ISSUE #537: Tasks can't handle quotes for Dockerfile in Build step
**Describe the bug**

If you have a step like:

```
steps: 
  - build: -f 'Dockerfile' -t 'xxxxx' .
```

It won't work as it will try to find a file named `'Dockerfile'` instead of `Dockerfile`. 

**To Reproduce**
You can run this task using the following YAML:

```
steps: 
  - build: -f 'Dockerfile' -t 'xxxxx' .
```
2019/10/26 01:24:40 Scanning for dependencies... 2019/10/26 01:24:41 Output from dependency scanning: error opening dockerfile: 'Dockerfile', error: open 'Dockerfile': no such file or directory

**Expected behavior**

It should be able to trim quotes and find the file.

**Screenshots**

**Any relevant environment information**
 - OS: [e.g. Windows]
 - Version [e.g. v1.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by jaysterp**
**Purpose of the PR**

- Allow the build step parser to handle quotes around arguments.

Fixes #537

### CODE REVIEW

File: util/trim.go [hunk 1]
```diff
@@ -0,0 +1,15 @@
+// Copyright (c) Microsoft Corporation. All rights reserved.
+// Licensed under the MIT License.
+
+package util
+
+import "strings"
+
+// TrimQuote returns a slice of the string s, with all leading
+// and trailing double or single quotes removed, as defined by Unicode.
+func TrimQuotes(s string) string {
```
Comment (northtyphoon) [inline util/trim.go]: I forgot to push my comment yesterday. I suggest use a function to trim multiple chars if it's your intention. /cc: @shahzzzam 

https://github.com/Azure/acr-builder/blob/685dad4e79a13d96b87d0e80a86751e777ab23af/builder/builder.go#L381
