### PR TITLE
fix alias issue + refactor some code

### LINKED ISSUE #511: Task unmarshaling fails with aliases
**Describe the bug**

**To Reproduce**

Run this task:

```
version: v1.1.0
alias:
  values:
    repo: myrepo
steps:
  - build: -t $Registry/$repo:$ID  -t $Registry/hello-world:$ID -f Dockerfile .
  - push:
    - "$Registry/hello-world:$ID"
```

1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Any relevant environment information**
 - OS: [e.g. Windows]
 - Version [e.g. v1.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by shahzzzam**
**Purpose of the PR**
Re-ordered steps for exec.

Steps:

1. Separate Alias data from task data
2. Render Alias data
3. Search/Replace alias data in task
4. Render templates
5. Unmarshal task to run
6. Expand command aliases

Touches up on #501 and #513.

Fixes #511

### CODE REVIEW

File: cmd/acb/commands/exec/exec.go [hunk 1]
```diff
@@ -201,55 +200,67 @@ var Command = cli.Command{
...
+		})
+		if errUnmarshal != nil {
+			return errors.Wrapf(errUnmarshal, "failed to unmarshal task from the string %s", rendered)
 		}
 
-		taskFinal, errUnmarshal := graph.UnmarshalTaskFromString(ctx, rendered, defaultWorkingDirectory, defaultNetwork, defaultEnvs, credentials, taskName, false)
-		if errUnmarshal != nil {
-			return errUnmarshal
+		if shouldIncludeAlias {
+			graph.ExpandCommandAliases(alias, task)
```
Comment (northtyphoon) [inline cmd/acb/commands/exec/exec.go]: >ExpandCommandAliases [](start = 9, length = 20)

the method is also called in task.NewTaskFromBytes

File: graph/task.go [hunk 2]
```diff
@@ -161,8 +182,7 @@ func NewTaskFromBytes(data []byte, doPreprocessing bool) (*Task, error) {
 			}
 			return t, err
 		}
```
Comment (northtyphoon) [inline graph/task.go]: It the code that throw the unmarshal error. But I don't see any logic change

File: cmd/acb/commands/exec/exec.go (hunk 1 above)
Comment (shahzzzam) [reply cmd/acb/commands/exec/exec.go]: yeah, not needed over there. Since now we have separated out the logic for 
SearchReplace
Expand.

File: cmd/acb/commands/exec/exec.go [hunk 3]
```diff
@@ -201,55 +200,67 @@ var Command = cli.Command{
...
 		var task *graph.Task
 		if shouldIncludeAlias {
 			log.Printf("Alias support enabled for version >= 1.1.0, please see https://aka.ms/acr/tasks/task-aliases for more information.")
-			// Generate the base task file without resolving environment variables.
-			task, err = graph.NewTaskFromBytes(template.GetData(), true)
-			if err != nil {
-				return err
-			}
+			// separate alias and remaining data
+			aliasData, remainingData := graph.SeparateAliasFromRest(template.GetData())
```
Comment (northtyphoon) [inline cmd/acb/commands/exec/exec.go]: >remainingData [](start = 14, length = 13)

nit: it's hard to tell what the variable names like  "remainingData" and "post" mean.

File: cmd/acb/commands/exec/exec.go [hunk 4]
```diff
@@ -201,55 +200,67 @@ var Command = cli.Command{
...
+			if renderAliasErr == nil {
+				aliasData = []byte(renderedAlias)
 
-			// Remarshal functional task file to resolve templating
-			var fromTask []byte
-			fromTask, err = yaml.Marshal(*task)
-			if err != nil {
-				return err
+				// Preprocess the task to replace all aliases based on the alias sources.
+				post, _alias, _, aliasErr := graph.SearchReplaceAlias(template.GetData(), aliasData, remainingData)
```
Comment (northtyphoon) [inline cmd/acb/commands/exec/exec.go]: >_, [](start = 18, length = 2)

if we don't use the return value, can it be removed?

File: cmd/acb/commands/exec/exec.go [hunk 5]
```diff
@@ -201,55 +200,67 @@ var Command = cli.Command{
...
+				alias = _alias
+				if aliasErr != nil {
+					log.Printf("unable to search/replace alias in task %s due to error %+v", post, aliasErr)
```
Comment (northtyphoon) [inline cmd/acb/commands/exec/exec.go]: >post, [](start = 78, length = 5)

I want to make sure we won't dump any secrets in log

File: graph/registry_credential.go [hunk 6]
```diff
@@ -37,6 +37,22 @@ type RegistryCredential struct {
 	AadResourceID string `json:"aadResourceId,omitempty"`
 }
 
+// CreateRegistryCredentialFromList creates a list of RegistryCredential
+// objects from list of serialized credentials.
+func CreateRegistryCredentialFromList(creds []string) ([]*RegistryCredential, error) {
```
Comment (northtyphoon) [inline graph/registry_credential.go]: >CreateRegistryCredentialFromList [](start = 5, length = 32)

add a test since it's public method

File: cmd/acb/commands/exec/exec.go [hunk 7]
```diff
@@ -201,55 +200,67 @@ var Command = cli.Command{
...
 			log.Printf("Alias support enabled for version >= 1.1.0, please see https://aka.ms/acr/tasks/task-aliases for more information.")
-			// Generate the base task file without resolving environment variables.
-			task, err = graph.NewTaskFromBytes(template.GetData(), true)
-			if err != nil {
-				return err
-			}
+			// separate alias and remaining data
+			aliasData, remainingData := graph.SeparateAliasFromRest(template.GetData())
+			// render alias data
+			values := templating.GetTaskRenderObject(renderOpts)
```
Comment (northtyphoon) [inline cmd/acb/commands/exec/exec.go]: >GetTaskRenderObject [](start = 24, length = 19)

GetTaskRenderObject only returns built-in values. I think alias also support custom values like

myAlias: {{.Values.MyValue}}?
