### PR TITLE
fix version parsing

### LINKED ISSUE #499: Parsing version from yaml file should account for space around ':'
**Describe the bug**

`version   :   v1.1.1` is also a valid yaml

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots**

**Any relevant environment information**
 - OS: [e.g. Windows]
 - Version [e.g. v1.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by shahzzzam**
**Purpose of the PR**

- 

Fixes #499

### CODE REVIEW

File: graph/preprocessor.go [hunk 1]
```diff
@@ -292,24 +294,26 @@ func basicAliasSeparation(data []byte) ([]byte, []byte) {
...
 		if trimmedText == "" || strings.HasPrefix(trimmedText, "#") {
 			continue
 		}
 
-		// use text instead of trimmedText since '   version: ' is also invalid.
-		if strings.HasPrefix(text, "version:") {
-			return strings.TrimSpace(strings.TrimPrefix(trimmedText, "version:"))
+		// use text instead of trimmedText since ' version: ' is also invalid.
+		if strings.HasPrefix(text, versionKey) {
+			tokens := strings.Split(text, ":")
```
Comment (juliusl) [inline graph/preprocessor.go]: What happens if the version is `version: "1.23.4:beta"` which is valid yaml?

Comment (juliusl) [reply graph/preprocessor.go]: Discussed offline, but for transparency recommendation is strings.SplitN or strings.SplitAfterN
